### ISSUE TITLE
OSError: [WinError 126] prevents batch processing

### ISSUE THREAD

**Issue by jskat** [Tierpsy/tierpsy-tracker#79]
Hi @luigiferiani,

I pulled the latest version of Tierpsy and followed the installation from source instructions with no problems aside from fixing the Qt plugin path error as I described [here](https://github.com/Tierpsy/tierpsy-tracker/issues/75). I can set parameters, but when I attempt to batch process a folder of videos, I encounter this error:
```
Traceback (most recent call last):
  File "c:\repos\tierpsy-tracker\tierpsy\gui\AnalysisProgress.py", line 62, in run
    self.worker_fun(**self.worker_args)
  File "c:\repos\tierpsy-tracker\tierpsy\processing\processMultipleFilesFun.py", line 129, in processMultipleFilesFun
    is_debug = is_debug)
OSError: [WinError 126] The specified module could not be found
```
In the corresponding processMultipleFilesFun.py file, line 129 is part of this code block:
```
if unmet_requirements:
        files_checker._printUnmetReq()
elif not only_summary:
    RunMultiCMD(
        cmd_list,
        local_obj = ProcessLocalParser,
        max_num_process = max_num_process,
        refresh_time = refresh_time,
        is_debug = is_debug)
```
The RunMultiCMD function comes from this import:
```
from tierpsy.processing.run_multi_cmd import RunMultiCMD
```
The run_multi_cmd.py file is in the same directory as processMultipleFilesFun.py and contains a lengthy RunMultiCMD function:
```
def RunMultiCMD(cmd_list,
                local_obj='',
                max_num_process=3,
                refresh_time=10,
                is_debug = True):
    '''Start different process using the command is cmd_list'''


    start_obj = partial(StartProcess, local_obj=local_obj, is_debug=is_debug)
# and so on...
```

StackOverflow has [a question with over 100k views](https://stackoverflow.com/questions/1940578/windowserror-error-126-the-specified-module-could-not-be-found) about WinError126. There seem to be a wide variety of possible causes, so I'm not sure what solution to try.

Any idea why this error is occurring?

**Comment by luigiferiani** [comment]
Hi @jskat,

unfortunately the RunMultiCMD function hides somewhat what actually goes, but there are a few things we can try to see if we can narrow down the issue:

1. is that the full traceback? if not, could you attach the full one?
2. does this happen even when you have the "only display progress summary" box ticked?
3. if running the "display progress summary" works, look at its output: there will be a very long list of commands, which are the ones that tierpsy uses under the hood to process each file individually. Could you try to copy one of those and paste it into a conda terminal (with tierpsy env active)? if the issue is due to an import, we should be able to understand what module is not being found

**Comment by jskat** [comment]
1. Here is the full output from the "Analysis Progress" window in the Tierpsy GUI:
```
Checking file 4 of 4. Total time: 0:00:00
*********************************************
Finished to check files.
Total time elapsed 0:00:00
*********************************************

*********************************************
Commands to be executed.
*********************************************
"C:\Users\j\miniconda3\envs\tierpsy\python.exe" "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\ProcessLocal.py" "C:\Users\j\Downloads\elegans\worm1_pt1.avi" --masks_dir "C:\Users\j\Downloads\elegans\MaskedVideos" --results_dir "C:\Users\j\Downloads\elegans\Results" --tmp_mask_dir "C:\Users\j\Tmp\MaskedVideos" --tmp_results_dir "C:\Users\j\Tmp\Results" --json_file "" --analysis_checkpoints "COMPRESS" "TRAJ_CREATE" "TRAJ_JOIN" "SKE_INIT" "BLOB_FEATS" "SKE_CREATE" "SKE_FILT" "SKE_ORIENT" "INT_PROFILE" "INT_SKE_ORIENT" "FEAT_INIT" "FEAT_TIERPSY"
"C:\Users\j\miniconda3\envs\tierpsy\python.exe" "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\ProcessLocal.py" "C:\Users\j\Downloads\elegans\worm1_pt2.avi" --masks_dir "C:\Users\j\Downloads\elegans\MaskedVideos" --results_dir "C:\Users\j\Downloads\elegans\Results" --tmp_mask_dir "C:\Users\j\Tmp\MaskedVideos" --tmp_results_dir "C:\Users\j\Tmp\Results" --json_file "" --analysis_checkpoints "COMPRESS" "TRAJ_CREATE" "TRAJ_JOIN" "SKE_INIT" "BLOB_FEATS" "SKE_CREATE" "SKE_FILT" "SKE_ORIENT" "INT_PROFILE" "INT_SKE_ORIENT" "FEAT_INIT" "FEAT_TIERPSY"
"C:\Users\j\miniconda3\envs\tierpsy\python.exe" "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\ProcessLocal.py" "C:\Users\j\Downloads\elegans\worm1_pt3.avi" --masks_dir "C:\Users\j\Downloads\elegans\MaskedVideos" --results_dir "C:\Users\j\Downloads\elegans\Results" --tmp_mask_dir "C:\Users\j\Tmp\MaskedVideos" --tmp_results_dir "C:\Users\j\Tmp\Results" --json_file "" --analysis_checkpoints "COMPRESS" "TRAJ_CREATE" "TRAJ_JOIN" "SKE_INIT" "BLOB_FEATS" "SKE_CREATE" "SKE_FILT" "SKE_ORIENT" "INT_PROFILE" "INT_SKE_ORIENT" "FEAT_INIT" "FEAT_TIERPSY"
"C:\Users\j\miniconda3\envs\tierpsy\python.exe" "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\ProcessLocal.py" "C:\Users\j\Downloads\elegans\worm1_pt4.avi" --masks_dir "C:\Users\j\Downloads\elegans\MaskedVideos" --results_dir "C:\Users\j\Downloads\elegans\Results" --tmp_mask_dir "C:\Users\j\Tmp\MaskedVideos" --tmp_results_dir "C:\Users\j\Tmp\Results" --json_file "" --analysis_checkpoints "COMPRESS" "TRAJ_CREATE" "TRAJ_JOIN" "SKE_INIT" "BLOB_FEATS" "SKE_CREATE" "SKE_FILT" "SKE_ORIENT" "INT_PROFILE" "INT_SKE_ORIENT" "FEAT_INIT" "FEAT_TIERPSY"
*********************************************

*********************************************
Analysis Summary
*********************************************
4	Unprocessed files.
0	Files whose analysis is incompleted.
0	Invalid source files.
0	Files that were succesfully finished.
*********************************************
4	Total files to be processed.
*********************************************
Traceback (most recent call last):
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\gui\AnalysisProgress.py", line 62, in run
    self.worker_fun(**self.worker_args)
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\processMultipleFilesFun.py", line 129, in processMultipleFilesFun
    is_debug = is_debug)
OSError: [WinError 126] The specified module could not be found
```

2. No, the error does not appear with "Only Display Progress Summary" checked.

3. I copied this command from the "Analysis Progress" output:
```
"C:\Users\j\miniconda3\envs\tierpsy\python.exe" "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\ProcessLocal.py" "C:\Users\j\Downloads\elegans\worm1_pt1.avi" --masks_dir "C:\Users\j\Downloads\elegans\MaskedVideos" --results_dir "C:\Users\j\Downloads\elegans\Results" --tmp_mask_dir "C:\Users\j\Tmp\MaskedVideos" --tmp_results_dir "C:\Users\j\Tmp\Results" --json_file "" --analysis_checkpoints "COMPRESS" "TRAJ_CREATE" "TRAJ_JOIN" "SKE_INIT" "BLOB_FEATS" "SKE_CREATE" "SKE_FILT" "SKE_ORIENT" "INT_PROFILE" "INT_SKE_ORIENT" "FEAT_INIT" "FEAT_TIERPSY"
```
and pasted it into my Anaconda prompt within the tierpsy environment, but received several errors (unrelated to the original problem) about "unexpected token in expression or statement."

As an alternative, I tried using tierpsy_process to process from command line.
```
tierpsy_process --video_dir_root "C:\Users\j\Downloads\elegans" --mask_dir_root "C:\Users\j\Downloads\elegans\MaskedVideos" --results_dir_root "C:\Users\j\Downloads\elegans\Results" --tmp_dir_root "C:\Users\j\Tmp\" --json_file "C:\Users\j\Downloads\reproducible_worms\parameters.json" --analysis_checkpoints "COMPRESS" "TRAJ_CREATE" "TRAJ_JOIN" "SKE_INIT" "BLOB_FEATS" "SKE_CREATE" "SKE_FILT" "SKE_ORIENT" "INT_PROFILE" "INT_SKE_ORIENT" "FEAT_INIT" "FEAT_TIERPSY" --pattern_include *.avi
```
This command started Tierpsy, which produced the following error message:
```
(tierpsy) PS C:\Users\j> tierpsy_process --video_dir_root "C:\Users\j\Downloads\elegans" --mask_dir_root "C:\Users\j\Downloads\elegans\MaskedVideos" --results_dir_root "C:\Users\j\Downloads\elegans\Results" --tmp_dir_root "C:\Users\j\Tmp\" --json_file "C:\Users\j\Downloads\reproducible_worms\parameters.json" --analysis_checkpoints "COMPRESS" "TRAJ_CREATE" "TRAJ_JOIN" "SKE_INIT" "BLOB_FEATS" "SKE_CREATE" "SKE_FILT" "SKE_ORIENT" "INT_PROFILE" "INT_SKE_ORIENT" "FEAT_INIT" "FEAT_TIERPSY" --pattern_include *.avi
Checking file 4 of 4. Total time: 0:00:01
*********************************************
Finished to check files.
Total time elapsed 0:00:01
*********************************************

*********************************************
Analysis Summary
*********************************************
4       Unprocessed files.
0       Files whose analysis is incompleted.
0       Invalid source files.
0       Files that were succesfully finished.
*********************************************
4       Total files to be processed.
*********************************************
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\j\miniconda3\envs\tierpsy\Scripts\tierpsy_process-script.py", line 11, in <module>
    load_entry_point('tierpsy', 'console_scripts', 'tierpsy_process')()
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\processMultipleFilesFun.py", line 133, in tierpsy_process
    processMultipleFilesFun(**vars(args))
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\processMultipleFilesFun.py", line 129, in processMultipleFilesFun
    is_debug = is_debug)
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\run_multi_cmd.py", line 126, in RunMultiCMD
    current_tasks.append(start_obj(cmd))
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\run_multi_cmd.py", line 48, in __init__
    self.cmd = self.obj_cmd.start()
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\ProcessLocal.py", line 89, in start
    self._copyFinaltoTmp()
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\ProcessLocal.py", line 124, in _copyFinaltoTmp
    inputs_required = self._points2Files(self.checkpoints2process, self.ap_tmp, "input_files")
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\ProcessLocal.py", line 248, in _points2Files
    data = ap_obj.getField(field_name, points_finished)
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\AnalysisPoints.py", line 115, in getField
    return {x : self.checkpoints[x][key] for x in points2get}
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\AnalysisPoints.py", line 115, in <dictcomp>
    return {x : self.checkpoints[x][key] for x in points2get}
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\AnalysisPoints.py", line 34, in __getitem__
    self._read_args(point)
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\processing\AnalysisPoints.py", line 40, in _read_args
    mod = import_module('tierpsy.analysis.' + point.lower())
  File "C:\Users\j\miniconda3\envs\tierpsy\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\analysis\ske_init\__init__.py", line 3, in <module>
    from .processTrajectoryData import processTrajectoryData
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\analysis\ske_init\processTrajectoryData.py", line 19, in <module>
    from tierpsy.analysis.ske_init.filterTrajectModel import filterModelWorms
  File "c:\users\j\downloads\reproducible_worms\tierpsy-tracker\tierpsy\analysis\ske_init\filterTrajectModel.py", line 18, in <module>
    import torch
  File "C:\Users\j\miniconda3\envs\tierpsy\lib\site-packages\torch\__init__.py", line 81, in <module>
    ctypes.CDLL(dll)
  File "C:\Users\j\miniconda3\envs\tierpsy\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```
It seems that the most recent import call was `import torch`?

Here is the output from `conda env export`:
```
name: tierpsy
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.9.0=py36h9f0ad1d_1
  - astor=0.7.1=py_0
  - blas=1.0=mkl
  - blosc=1.18.1=h6538335_0
  - brotlipy=0.7.0=py36h68aa20f_1001
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2020.4.5.1=hecc5488_0
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - cffi=1.14.0=py36ha419a9e_0
  - chardet=3.0.4=py36hd36e781_1008
  - cloudpickle=1.4.1=py_0
  - cryptography=2.9.2=py36hef61171_0
  - cudatoolkit=10.2.89=hb195166_9
  - cycler=0.10.0=py_2
  - cython=0.29.19=py36h003fed8_0
  - cytoolz=0.10.1=py36hfa6e2cd_0
  - dask-core=2.16.0=py_0
  - decorator=4.4.2=py_0
  - ffmpeg=4.2.3=ha925a31_0
  - freetype=2.10.2=hd328e21_0
  - gast=0.3.3=py_0
  - grpcio=1.23.0=py36hc6b9980_1
  - h5py=2.10.0=nompi_py36h422b98e_102
  - hdf5=1.10.5=nompi_h4d922ce_1114
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=64.2=he025d50_1
  - idna=2.9=py_1
  - imagecodecs-lite=2019.12.3=py36h6434af4_3
  - imageio=2.8.0=py_0
  - importlib-metadata=1.6.0=py36h9f0ad1d_0
  - intel-openmp=2019.4=245
  - joblib=0.15.1=py_0
  - jpeg=9c=hfa6e2cd_1001
  - keras=2.1.5=py36_0
  - kiwisolver=1.2.0=py36hdbb1a49_1
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libclang=9.0.1=default_h5c34c98_2
  - libgpuarray=0.7.6=h8ffe710_1003
  - liblapack=3.8.0=14_mkl
  - liblapacke=3.8.0=14_mkl
  - libopencv=4.2.0=py36_6
  - libpng=1.6.37=h1d00b33_2
  - libprotobuf=3.11.4=h1a1b453_0
  - libtiff=4.1.0=h885aae3_6
  - libwebp=1.0.2=hfa6e2cd_5
  - libzlib=1.2.11=h8ffe710_1013
  - llvmlite=0.31.0=py36h9f0ad1d_1
  - lz4-c=1.9.2=h62dcd97_2
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mako=1.1.0=py_0
  - markdown=3.2.2=py_0
  - markupsafe=1.1.1=py36h68aa20f_3
  - matplotlib=3.2.1=0
  - matplotlib-base=3.2.1=py36hf0cddfc_0
  - mkl=2019.4=245
  - mkl-service=2.3.0=py36hfa6e2cd_0
  - mock=4.0.2=py36h9f0ad1d_1
  - msys2-conda-epoch=20160418=1
  - networkx=2.4=py_1
  - ninja=1.9.0=h1ad3211_1
  - numba=0.48.0=py36he350917_0
  - numexpr=2.7.1=py36hd7f5668_3
  - numpy=1.18.4=py36h4d86e3b_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.2.0=py36_6
  - openssl=1.1.1g=he774522_1
  - pandas=0.25.3=py36he350917_0
  - patsy=0.5.1=py_0
  - pillow=7.1.2=py36he4e95fe_0
  - pip=20.1.1=py_1
  - protobuf=3.11.4=py36h97ec31f_1
  - py-opencv=4.2.0=py36h95af2a2_6
  - pycparser=2.20=pyh9f0ad1d_2
  - pygpu=0.7.6=py36h6434af4_1002
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyhd8ed1ab_1
  - pyqt=5.12.3=py36h6538335_1
  - pyreadline=2.1=py36ha15d459_1004
  - pysocks=1.7.1=py36ha15d459_3
  - pytables=3.6.1=py36h26f9782_1
  - python=3.6.10=he025d50_1009_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=2_cp36m
  - pytorch=1.5.0=py3.6_cuda102_cudnn7_0
  - pytz=2020.1=pyh9f0ad1d_0
  - pywavelets=1.1.1=py36h6434af4_3
  - pyyaml=5.3.1=py36h68a101e_0
  - qt=5.12.5=h7ef1ec2_0
  - requests=2.23.0=pyh8c360ce_2
  - scikit-image=0.17.2=py36he38d939_4
  - scikit-learn=0.23.1=py36h13569b7_0
  - scipy=1.3.1=py36h29ff71c_0
  - setuptools=46.4.0=py36h9f0ad1d_0
  - six=1.14.0=py_1
  - sqlite=3.30.1=hfa6e2cd_0
  - statsmodels=0.11.1=py36h779f372_2
  - tensorboard=1.10.0=py36_0
  - tensorflow=1.10.0=py36_0
  - termcolor=1.1.0=py_2
  - theano=1.0.4=py36h003fed8_1002
  - threadpoolctl=2.0.0=pyh5ca1d4c_0
  - tifffile=2020.5.11=py_0
  - tk=8.6.10=h8ffe710_1
  - toolz=0.10.0=py_0
  - torchvision=0.6.0=py36_cu102
  - tornado=6.0.4=py36h779f372_2
  - tqdm=4.46.0=pyh9f0ad1d_0
  - urllib3=1.25.9=py_0
  - vc=14.1=h869be7e_1
  - vs2015_runtime=14.16.27012=h30e32a0_2
  - vs2015_win-64=14.0.25420=h55c1224_11
  - vs2017_win-64=19.16.27033=hb90652a_6
  - vswhere=3.0.1=h57928b3_0
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.34.2=py_1
  - win_inet_pton=1.1.0=py36ha15d459_2
  - wincertstore=0.2=py36ha15d459_1006
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.4=he774522_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h8ffe710_1013
  - zstd=1.4.4=h9f78265_3
  - pip:
    - imgstore==0.2.9
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12.0
    - pyqtwebengine==5.12.1
    - tzlocal==2.1
variables:
  QT_PLUGIN_PATH: C:\Users\j\miniconda3\envs\tierpsy\Library\plugins
prefix: C:\Users\j\miniconda3\envs\tierpsy
```
It appears that the environment already has PyTorch. I must be misinterpreting the error message.

**Comment by luigiferiani** [comment]
ah @jskat this is perfect, thank you - this triggered my memory actually, sorry, I should have remembered sooner. It's an issue that happens if the Window machine does not have a CUDA enabled GPU. 

The solution is to install the cpu-only version of pytorch - see the fix is at the end of this page:
https://github.com/Tierpsy/tierpsy-tracker/blob/development/docs/ISSUES.md

**Comment by jskat** [comment]
Great, that solves the problem! Thank you.
