### ISSUE TITLE
HDF5 file unable to be created/opened

### ISSUE THREAD

**Issue by Jing0283** [Tierpsy/tierpsy-tracker#88]
I met this issue during Batch Processing Multiple Files, using both the example files as well as my own local files (in .avi and .mp4 format)
ERROR: 
Unable to open/create file '/home/tierpsy_user/Tmp/MaskedVideos/cam2+ob1-1.hdf5'
Traceback (most recent call last):
  File "/tierpsy-tracker/tierpsy/processing/ProcessWorker.py", line 108, in <module>
    ProcessWorker(**args, cmd_original = subprocess.list2cmdline(sys.argv))
  File "/tierpsy-tracker/tierpsy/processing/ProcessWorker.py", line 38, in __init__
    self.execAllPoints()
  File "/tierpsy-tracker/tierpsy/processing/ProcessWorker.py", line 66, in execAllPoints
    cmd_original = self.cmd_original)
  File "/tierpsy-tracker/tierpsy/processing/trackProvenance.py", line 28, in execThisPoint
    func(**argkws)
  File "/tierpsy-tracker/tierpsy/analysis/compress/processVideo.py", line 142, in processVideo
    compressVideo(video_file, masked_image_file, **compress_vid_param)
  File "/tierpsy-tracker/tierpsy/analysis/compress/compressVideo.py", line 243, in compressVideo
    save_full_interval = save_full_interval)
  File "/tierpsy-tracker/tierpsy/helper/params/get_defaults.py", line 48, in compress_defaults
    fps = _read_correct_fps(fname, expected_fps)
  File "/tierpsy-tracker/tierpsy/helper/params/get_defaults.py", line 23, in _read_correct_fps
    fps_out = read_unit_conversions(fname)[0]
  File "/tierpsy-tracker/tierpsy/helper/params/read_attrs.py", line 188, in read_unit_conversions
    reader = AttrReader(fname, dflt)
  File "/tierpsy-tracker/tierpsy/helper/params/read_attrs.py", line 54, in __init__
    self.field =  self._find_field()
  File "/tierpsy-tracker/tierpsy/helper/params/read_attrs.py", line 59, in _find_field
    with tables.File(self.file_name, 'r') as fid:
  File "/home/tierpsy_user/.local/lib/python3.6/site-packages/tables/file.py", line 778, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1400, in H5F__open
    unable to open file
  File "H5Fint.c", line 1615, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1640, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

I have checked the temporary dir box and all other processes have been ceased to prioritise this analysing process. 

Thank you very much for the help!

**Comment by Jing0283** [comment]
I'm using Windows 11. The docker installation and tierpsy.ps1 creation have been successful by far.

**Comment by WeheliyeHashi** [comment]
Hi Jing, make sure to use a 'include pattern' that matches your video types :) reading from the text you posted here (thanks for including that) it was *.hdf5, it should work for your Avi videos if you set it to *.avi.

**Comment by WeheliyeHashi** [comment]
fixed
