### ISSUE TITLE
packages conflicts in source installation on Windows 11

### ISSUE THREAD

**Issue by monfort314** [Tierpsy/tierpsy-tracker#92]
Hi!
I cloned the repo successfully but when I tried to create the environment with 

`conda env create -f 
tierpsy_windows.yml`

I got an error
```
Could not solve for environment specs
The following packages are incompatible
├─ h5py 2.10.0**  is installable with the potential options
│  ├─ h5py 2.10.0 would require
│  │  └─ python_abi * *_cp36m, which can be installed;
│  ├─ h5py 2.10.0 would require
│  │  └─ hdf5 >=1.10.6,<1.10.7.0a0 , which can be installed;
│  ├─ h5py 2.10.0 would require
│  │  └─ python_abi * *_cp37m, which can be installed;
│  ├─ h5py 2.10.0 would require
│  │  └─ python_abi * *_cp38, which can be installed;
│  └─ h5py 2.10.0 would require
│     └─ hdf5 >=1.10.4,<1.10.5.0a0 , which can be installed;
├─ hdf5 1.10.5**  is not installable because it conflicts with any installable versions previously reported;
├─ openssl 1.1.1g**  is requested and can be installed;
├─ python 3.6.10**  is requested and can be installed;
├─ python_abi 3.6**  is not installable because it conflicts with any installable versions previously reported;
├─ pytorch 1.5.0**  is not installable because it requires
│  └─ python >=3.7,<3.8.0a0  but there are no viable options
│     ├─ python [3.7.0|3.7.1|...|3.7.9] conflicts with any installable versions previously reported;
│     ├─ python [3.7.10|3.7.12] would require
│     │  └─ python_abi 3.7 *_pypy37_pp73, which conflicts with any installable versions previously reported;
│     ├─ python 3.7.10 would require
│     │  └─ openssl >=1.1.1j,<1.1.2a , which conflicts with any installable versions previously reported;
│     ├─ python [3.7.10|3.7.12] would require
│     │  └─ openssl >=1.1.1l,<1.1.2a , which conflicts with any installable versions previously reported;
│     ├─ python [3.7.10|3.7.12] would require
│     │  └─ openssl >=3.0.0,<4.0a0 , which conflicts with any installable versions previously reported;
│     ├─ python [3.7.5|3.7.9] would require
│     │  └─ openssl >=1.1.1i,<1.1.2a , which conflicts with any installable versions previously reported;
│     ├─ python [3.7.8|3.7.9] would require
│     │  └─ openssl >=1.1.1h,<1.1.2a , which conflicts with any installable versions previously reported;
│     ├─ python 3.7.11 would require
│     │  └─ openssl >=1.1.1k,<1.1.2a , which conflicts with any installable versions previously reported;
│     ├─ python 3.7.13 would require
│     │  └─ openssl >=1.1.1n,<1.1.2a , which conflicts with any installable versions previously reported;
│     ├─ python 3.7.13 would require
│     │  └─ openssl >=1.1.1q,<1.1.2a , which conflicts with any installable versions previously reported;
│     └─ python [3.7.15|3.7.16] would require
│        └─ openssl >=1.1.1s,<1.1.2a , which conflicts with any installable versions previously reported;
└─ torchvision 0.6.0**  does not exist (perhaps a typo or a missing channel).
```

Removing the versions constrains from tierpsy_windows.yml file resulted in issues with finding Qt plugin:
```qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized.```  

I'm using 
conda 23.10.0
pip 23.2.1
on Windows 11

Do you have any suggestions how to solve this?

**Comment by WeheliyeHashi** [comment]
For windows, we recommend using the Docker installation:

https://github.com/Tierpsy/tierpsy-tracker/blob/development/docs/INSTALLATION_DOCKER.md

**Comment by monfort314** [comment]
Thanks for the reply! I tried this one too but it seems that every time I try to run power shell it gets automatically terminated, and when I try to run the docker container, it exits automatically. It is possible that we have some institutional blockade to run files through docker. 
I tried the conda installation too, gui generally works, so does the parameters selection but when I try to run batch processing, I almost immediately get an error 
```
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\tierpsy2\lib\site-packages\tierpsy\gui\AnalysisProgress.py", line 62, in run
    self.worker_fun(**self.worker_args)
  File "C:\ProgramData\anaconda3\envs\tierpsy2\lib\site-packages\tierpsy\processing\processMultipleFilesFun.py", line 129, in processMultipleFilesFun
    is_debug = is_debug)
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

**Comment by WeheliyeHashi** [comment]
for the Docker, have you tried the following command:
docker pull tierpsy/tierpsy-tracker

If so do you get an error or does it exit.

**Comment by WeheliyeHashi** [comment]
Could you send me your parameters file that you tried to use for the batch processing along with the videos. (weheliye@ic.ac.uk)

For the gui version, try creating a new parameters file and use that for your batch processing.

**Comment by WeheliyeHashi** [comment]
No responses was received for this issue. This will be closed!
