### ISSUE TITLE
metaclass error

### ISSUE THREAD

**Issue by monfort314** [Tierpsy/tierpsy-tracker#96]
Hi! Actually we experienced the same error as already metioned, despite of having the right python version installed. 

This happens when following conda installation, in the step where we try to process batch, we get an error:

Traceback (most recent call last):
File "C:\Users\*\AppData\Local\anaconda3\envs\tierpsy\lib\site-packages\tierpsy\gui\AnalysisProgress.py", line 62, in run
self.worker_fun(**self.worker_args)
File "C:\Users\*\AppData\Local\anaconda3\envs\tierpsy\lib\site-packages\tierpsy\processing\processMultipleFilesFun.py", line 129, in processMultipleFilesFun
is_debug = is_debug)
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

Alternatively, when installing the environment from .yaml file 
conda env create -f tierpsy_tracker.yml

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested torchvision 0.6.0**
  - package pytorch-1.5.0-cpu_py37h9f948e0_0 requires vc >=14.1,<15.0a0, but none of the providers can be installed
  
  We use Windows 10 and installation with Docker is not an option due to IT blockade.

_Originally posted by @monfort314 in https://github.com/Tierpsy/tierpsy-tracker/issues/93#issuecomment-2517285433_

**Comment by monfort314** [comment]
Hi Again, So we actually managed to resolve it with updated yml file (attached, some packages versions needed to be modified) and then setting the path to qwindows.dll: for some reason it was not set up correctly after installing pyqt/qt - not sure why but it was easy to fix
[tierpsy_windows_Ola.yml.txt](https://github.com/user-attachments/files/18021403/tierpsy_windows_Ola.yml.txt)
